"""Abstract storage interface — swap LocalStorage for S3Storage for cloud."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    def write(self, session_id: str, filename: str, data: bytes) -> None: ...
    def read(self, session_id: str, filename: str) -> bytes: ...
    def exists(self, session_id: str, filename: str) -> bool: ...
    def list_sessions(self) -> list[str]: ...
    def delete_session(self, session_id: str) -> None: ...
